"""plan_limits_domain_uniqueness_ownership

Revision ID: 58b5625d8b68
Revises: 
Create Date: 2026-06-18 15:57:45.776247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b5625d8b68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Deduplicate domains before enforcing uniqueness.
    # For each domain name that appears on multiple tenants, keep the row with
    # the earliest added_at (original owner) and delete the rest.
    op.execute("""
        DELETE FROM domains
        WHERE id IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY name
                           ORDER BY added_at ASC NULLS LAST
                       ) AS rn
                FROM domains
            ) ranked
            WHERE rn > 1
        )
    """)

    op.add_column('domains', sa.Column('ownership_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_unique_constraint('uq_domains_name', 'domains', ['name'])
    op.add_column('tenants', sa.Column('billing_email', sa.String(length=320), nullable=True))
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('brand_name', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('brand_logo_url', sa.String(length=500), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'brand_logo_url')
    op.drop_column('tenants', 'brand_name')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'billing_email')
    op.drop_constraint('uq_domains_name', 'domains', type_='unique')
    op.drop_column('domains', 'ownership_verified')
    # ### end Alembic commands ###
