"""add_msp_parent_tenant

Revision ID: 99398824a86b
Revises: 3212a71db6e0
Create Date: 2026-06-18 16:15:27.978285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99398824a86b'
down_revision: Union[str, None] = '3212a71db6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('parent_tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tenants_parent_tenant_id'), 'tenants', ['parent_tenant_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'tenants', ['parent_tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_parent_tenant_id'), table_name='tenants')
    op.drop_column('tenants', 'parent_tenant_id')
    # ### end Alembic commands ###
