"""add_stripe_subscription_id

Revision ID: c31e0f2267d3
Revises: 99398824a86b
Create Date: 2026-06-18 16:29:22.646934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31e0f2267d3'
down_revision: Union[str, None] = '99398824a86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'stripe_subscription_id')
    # ### end Alembic commands ###
